### ISSUE TITLE
Fails to build with Boost 1.58.0

### ISSUE THREAD

**Issue by jwakely** [luceneplusplus/LucenePlusPlus#100]
There is a breaking change to Boost.Variant in 1.58.0 which breaks the `get` function in LucenePlusPlus-rel_3.0.7/include/VariantUtils.h

It can be fixed by changing `boost::get` to `boost::relaxed_get` on line 25 but that probably won't compile with older versions of Boost, so an alternative solution is to define `BOOST_VARIANT_USE_RELAXED_GET_BY_DEFAULT` to change the default behaviour.

See http://www.boost.org/doc/libs/1_58_0/doc/html/boost/get_idp295310448.html for details.

**Comment by vslavik** [comment]
This was fixed by a64e24f3b5ac58e65fb965ee44d9841c98087223 and can be closed.
