### ISSUE TITLE
Comparing with apache Lucene 8.2.0，which is more faster？

### ISSUE THREAD

**Issue by kenghuang** [luceneplusplus/LucenePlusPlus#130]
LucenePlusPlus is good，but we can not get  a performance test data or benchmark with lucene？

**Comment by mdianjun** [comment]
Why this issue is closed?  I couldn't find any benchmark at all. @alanw

**Comment by keywan-ghadami** [comment]
@mdianjun back in time I used it was a huge performance difference but I do not have benchmarks. maybe have a look at 
https://github.com/tantivy-search/tantivy
they implement a search in rust and do have good performance. if rust or a binding to rust is acceptable for your task of cause.
if so you will find benchmarks here:
https://tantivy-search.github.io/bench/
are much bigger community I guess.

**Comment by mdianjun** [comment]
> @mdianjun back in time I used it was a huge performance difference but I do not have benchmarks. maybe have a look at
> https://github.com/tantivy-search/tantivy
> they implement a search in rust and do have good performance. if rust or a binding to rust is acceptable for your task of cause.
> if so you will find benchmarks here:
> https://tantivy-search.github.io/bench/
> are much bigger community I guess.

@keywan-ghadami Thank you, I have been comparing tantivy and lucene++ for several days. Tantivy community is bigger and more active, but the defect of it is the limitation of query grammar,  which only supports phrase query and logical expression query, lacking of more complex query, e.g. fuzzy query, range query. So I am confused.
