### ISSUE TITLE
How to extract the total number of matches for each document

### ISSUE THREAD

**Issue by sinaviw592** [luceneplusplus/LucenePlusPlus#141]
I'm new to lucene, so i don't know if this is possible, how to extract the total number of matches for each document?

**Comment by alanw** [comment]
Hi,

[Instructions](https://stackoverflow.com/a/12791565/12854301) for finding total number of matches using [ScorerVisitor](https://github.com/luceneplusplus/LucenePlusPlus/blob/b7baba57d9bab88dde4e9569ffa14885d8b575eb/include/Scorer.h#L17).

Hope this helps.
