### ISSUE TITLE
[REGRESSION] CompoundFileTest failure

### ISSUE THREAD

**Issue by p01arst0rm** [luceneplusplus/LucenePlusPlus#145]
running test suite results in the CompoundFileTest.testClonedStreamsClosing
test failing.

**Comment by alanw** [comment]
Any ideas what caused this regression? (same applies to #146)

**Comment by p01arst0rm** [comment]
no clue, just got the test suites running properly and it seems to have failed. ill start looking into it for you

**Comment by p01arst0rm** [comment]
more info on the failure:
```
/home/p01ar/LucenePlusPlus/src/test/index/CompoundFileTest.cpp:325: Failure
Value of: !isCSIndexInputOpen(one)
  Actual: false
Expected: true
/home/p01ar/LucenePlusPlus/src/test/index/CompoundFileTest.cpp:326: Failure
Value of: !isCSIndexInputOpen(two)
  Actual: false
Expected: true
```
