### ISSUE TITLE
[REGRESSION] IndexReaderTest failure

### ISSUE THREAD

**Issue by p01arst0rm** [luceneplusplus/LucenePlusPlus#146]
running test suite results in the IndexReaderTest.testDeleteReaderWriterConflictOptimized
test failing.

**Comment by p01arst0rm** [comment]
more info on the failure:

```
unknown file: Failure
C++ exception with description "LuceneException[9]: Failed to read from file: ../src/test/testfiles/temp/testIndex/_2.cfs" thrown in the test body.
```

**Comment by alanw** [comment]
Hmm, this is quite concerning. I'm not sure what's changed that would make these unit tests fail (?)

**Comment by p01arst0rm** [comment]
imo looks like a test file has gone walkies? says it cant find a cfs, and that cfs indeed is not in the temp dir. probably a case of going back through history to find when it started failing.

**Comment by p01arst0rm** [comment]
nice one! :D
