### ISSUE TITLE
Shold define MMapIndexInput file length as int32_t?

### ISSUE THREAD

**Issue by ThatisOK** [luceneplusplus/LucenePlusPlus#156]
the range of int32_t is -2147483648~2147483647, that means the max size of a file is 2.14GB.
Is this a meaningful limit? or the mmap limit is 2.14G?

if size of a file is larger than 2.14G, it will map fail and throw a FileNotFoundException, is this right?

![image](https://user-images.githubusercontent.com/3744853/91520644-4e7a1580-e8e5-11ea-967c-18f1329c5d8b.png)

**Comment by alanw** [comment]
I believe the max shard size is 2^32 so `int32_t` should be enough
