### ISSUE TITLE
Is LucenePlusPlus ported till the latest release of apache lucene?

### ISSUE THREAD

**Issue by abhishekamte** [luceneplusplus/LucenePlusPlus#159]
hello,

Does LucenePlusPlus have all the features till the current latest release of apache lucene v8.6.3? I ask because i couldnt find any documentation of it in the repo, also the the latest release tag corresponds to a commit of 2015.

Thanks!

**Comment by chris-caat** [comment]
Yes, this is the first question someone interested in this project is going to ask. You should have this correspondence info on the main project page.

**Comment by alanw** [comment]
This project is maintained on a best-effort basis as I have other commitments that take a lot of my time.

I've updated the version details to reflect the changes since 2015.

**Comment by grapevineai** [comment]
@alanw Does it mean that it refers to Lucene v8? Just mentioning this on the README would be helpful as there is no reference to any API.

Thank you so much for the hard work and thanks for sharing this amazing library!
