### ISSUE TITLE
Will the API remain compatible with the java version?

### ISSUE THREAD

**Issue by chenyang8094** [luceneplusplus/LucenePlusPlus#177]
At present, LucenePlusPlus has a lot of differences from the java version. Many new features have been added to java, and some APIs have been abandoned. Does LucenePlusPlus currently have plans to be compatible with these changes? @alanw

**Comment by alanw** [comment]
Hi Chenyang, this project is maintained on a best-effort basis as I have other commitments that take a lot of my time.
