### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by boussouira** [luceneplusplus/LucenePlusPlus#89]
Hi,
I want to know is this project is active and if it implement all Java Lucene features.
Thank you

**Comment by gbjbaanb** [comment]
I can't answer either - but the code works quite nicely.

**Comment by alanw** [comment]
Sorry for the delay boussouira,

Yes the project is active, but I don't have a great deal of time to dedicate to this right now.

As for the features it supports - It supports almost all features of Java Lucene version 3.0.
